#!/usr/bin/env bash

command=${1:-run}
target=${2:-vf2}

TOOL_CHAIN_PREFIX=./xpacks/.bin/riscv-none-elf
BIN_DIR=zig-out/bin
BIN_FILE=${BIN_DIR}/kernel.bin

PATH=tools/bin:$PATH

function download_nezha () {
    echo "Download to Nezha"
    xfel version && xfel ddr d1
    test $? -eq 0 || exit
    set -x
    serial-term &
    xfel write 0x40000000 ${BIN_FILE} 
    { set +x; } 2>/dev/null
    sleep 2
    xfel exec 0x40000000
}

function download_vf2 () {
    echo "Download to VisionFive2"
    set -x
    spl_tool -c -f ${BIN_FILE}
    vf2flash -l 0 -t -f ${BIN_FILE}.normal.out
    { set +x; } 2>/dev/null
}

function download () {
    if [[ "${target}" == "nezha" ]]; then
        download_nezha
    fi

    if [[ "${target}" == "vf2" ]]; then
        download_vf2
    fi
}

function build () {
    rm $BIN_DIR/*
    set -x
    zig build kernel -Dboard="${target}"
    ${TOOL_CHAIN_PREFIX}-objdump -h -d -S ${BIN_DIR}/kernel.elf > ${BIN_DIR}/kernel.elf.objdump
    { set +x; } 2>/dev/null
}

if [ "$command" == "build" ]; then
    build
elif [ "$command" == "download" ]; then
    download
else
    build
    download
fi


